trigger:
  branches:
    include:
    - 'main'

stages:
- stage: Build
  displayName: 'Build and publish infrastructure artifacts'
  jobs:
  - template: templates/psrule.yaml
    parameters:
      psRuleModules: 'PSRule.Rules.Azure,PSRule.Rules.CAF'
      psRuleBaseline: 'Azure.GA_2024_03'
  - template: 'templates/build.yaml'

- template: 'templates/deploy.yaml'
  parameters:
    devOpsEnvironmentName: 'Development Infrastructure'
    environmentName: 'Development'
    agentPoolName: 'bicusa_brint_agent_dev'
    region: eastus2
    resourceGroupName: bicusa-int-dev
    serviceConnectionName: 'bicusa-int-dev-sp01'
    deployFoundation: true
    deployMain: true
 
  
- template: 'templates/deploy.yaml'
  parameters:
    devOpsEnvironmentName: 'Test Infrastructure'
    environmentName: 'Test'
    agentPoolName: 'bicusa_brint_agent_dev'
    region: eastus2
    resourceGroupName: bicusa-int-test
    serviceConnectionName: 'bicusa-int-dev-sp01'
    deployFoundation: false
    deployMain: false

- template: 'templates/deploy.yaml'
  parameters:
    devOpsEnvironmentName: 'Production Infrastructure'
    environmentName: 'Production'
    agentPoolName: 'bicusa_brint_agent_dev'
    region: eastus2
    resourceGroupName: bicusa-int-prod
    serviceConnectionName: 'bicusa-int-dev-sp01'
    deployFoundation: false
    deployMain: false
